# Generated by Django 5.0.4 on 2025-05-07 10:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_address_unique_default_address_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telephone must contain only digits.', regex='^\\d+$')]),
        ),
        migrations.AddConstraint(
            model_name='userpaymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_payment_per_user'),
        ),
    ]
