services:
  # Frontend Service
  - type: web
    name: cn334-frontend
    env: node
    region: singapore
    rootDir: app_frontend
    # แก้ไข buildCommand เป็นอันนี้:
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_USER_API_URL
        value: https://cn334-user-service.onrender.com
      - key: NEXT_PUBLIC_PRODUCT_API_URL
        value: https://cn334-product-service.onrender.com

  # User Service (Django/Python)
  - type: web
    name: cn334-user-service
    env: docker
    region: singapore
    dockerfilePath: ./user_service/Dockerfile
    dockerContext: ./user_service
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_SETTINGS_MODULE
        value: user_service.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: cn334-user-service.onrender.com
      - key: PORT
        value: "8000"

  # Product Service (Django/Python)
  - type: web
    name: cn334-product-service
    env: docker
    region: singapore
    dockerfilePath: ./product_service/Dockerfile
    dockerContext: ./product_service
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_SETTINGS_MODULE
        value: product_service.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: cn334-product-service.onrender.com
      - key: PORT
        value: "8000"

  # App Service
  - type: web
    name: cn334-app
    env: docker
    region: singapore
    dockerfilePath: ./app_frontend/Dockerfile
    dockerContext: ./app_frontend
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://cn334-app.onrender.com
