# Generated by Django 5.0.4 on 2025-05-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_remove_payment_user_payment_method_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'ตะกร้า'), ('pending', 'รอชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('processing', 'กำลังเตรียมของ'), ('in_transit', 'กำลังจัดส่ง'), ('shipped', 'จัดส่งแล้ว')], default='pending', max_length=100),
        ),
    ]
