# Generated by Django 5.0.4 on 2025-05-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'บัตรเครดิต/เดบิต'), ('cash_on_delivery', 'เก็บเงินปลายทาง'), ('qr_code', 'สแกน QR Code')], default='cash_on_delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
