# Generated by Django 5.0.4 on 2025-05-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_order_payment_method_order_qr_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qr_reference',
        ),
    ]
